spring:
  datasource:
    url: jdbc:h2:./database
    username: sa
    password:

  jpa:
    show-sql: true
    open-in-view: false
    properties.hibernate:
      format_sql: true
      default_batch_fetch_size: 20
      jdbc.batch_size: 20

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

logging:
  file.name: ./log/voting.log

springdoc:
  api-docs.path: /api-docs

access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
accessTimeOfMinutes: 30
refreshTimeOfMinutes: 60