spring:
  datasource:
    url: jdbc:h2:./database
    username: sa
    password:

  sql:
    init.mode: always

  jpa:
    show-sql: true
    open-in-view: false
    properties.hibernate:
      format_sql: true
      default_batch_fetch_size: 20
      jdbc.batch_size: 20

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

logging:
  file.name: ./log/voting.log